### ISSUE TITLE
`config.yaml` and `settings.yaml` are not properly merged

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/ethics-vehicles-2#6]
When adjusting the `buttonPositions` in `settings.yaml`, the resulting config contains the concatenation of the two coordinate arrays.

Example:
```yaml
buttonPositions:
  button-1: [800, 1855]
...
```
and
```yaml
buttonPositions:
  button-1: [900, 1855]
```
are merged to
```yaml
buttonPositions:
  button-1: [800, 1855, 900, 1855]
...
```
and not to the expected result of
```yaml
buttonPositions:
  button-1: [900, 1855]
```
